<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">demo_repo.html</title>
      <link href="assets\style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">demo_repo.html</h1>
    <p>Report generated on 26-Apr-2024 at 22:51:31 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">1 test took 00:02:53.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" />
            <span class="failed">1 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" disabled/>
            <span class="passed">0 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" disabled/>
            <span class="skipped">0 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" disabled/>
            <span class="xpassed">0 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" disabled/>
            <span class="error">0 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.12.3&#34;, &#34;Platform&#34;: &#34;Windows-10-10.0.19045-SP0&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;8.1.1&#34;, &#34;pluggy&#34;: &#34;1.4.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;metadata&#34;: &#34;3.1.1&#34;}, &#34;JAVA_HOME&#34;: &#34;C:\\Program Files\\Java\\jdk-17&#34;}, &#34;tests&#34;: {&#34;testcases/test_searchflights.py::TestSearchFlights::test_search_flights_1stop_1___New_Delhi____New_York____29_04_2024___1_&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Failed&#34;, &#34;testId&#34;: &#34;testcases/test_searchflights.py::TestSearchFlights::test_search_flights_1stop_1___New_Delhi____New_York____29_04_2024___1_&#34;, &#34;duration&#34;: &#34;00:02:53&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Failed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;testcases/test_searchflights.py::TestSearchFlights::test_search_flights_1stop_1___New_Delhi____New_York____29_04_2024___1_&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:53&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;self = &amp;lt;testcases.test_searchflights.TestSearchFlights testMethod=test_search_flights_1stop_1___New_Delhi____New_York____29_04_2024___1_&amp;gt;\ndepartfrom = &amp;#x27;New Delhi&amp;#x27;, departto = &amp;#x27;New York&amp;#x27;, departdate = &amp;#x27;29/04/2024&amp;#x27;, stop = 1\n\n    @data(*(Util.read_data_from_excel(&amp;quot;C:\\\\pycharm-projects\\\\TestFramworkDemo\\\\testdata\\\\test_d.xlsx&amp;quot;, &amp;quot;Sheet1&amp;quot;)))\n    @unpack\n    def test_search_flights_1stop(self, departfrom, departto, departdate, stop):\n        search_flight_result = self.lp.search_flights(departfrom, departto, departdate)\n        self.lp.scroll_To_infinitepage()\n        all_stops = search_flight_result.searchflightresults(stop)\n&amp;gt;       self.ut.asserListItems(all_stops, stop)\n\ntestcases\\test_searchflights.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities\\utilities.py:28: in asserListItems\n    self.assert_all()\nC:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(&amp;#x27;&amp;#x27;.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 63 failures were found in &amp;quot;wrapper&amp;quot; (utilities.utilities.Util):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [1/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [2/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 3 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [3/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 4 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [4/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 5 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [5/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 6 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [6/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 7 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [7/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 8 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [8/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 9 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [9/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 10 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [10/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 11 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [11/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 12 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [12/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 13 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [13/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 14 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [14/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 15 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [15/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 16 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [16/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 17 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [17/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 18 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [18/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 19 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [19/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 20 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [20/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 21 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [21/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 22 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [22/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 23 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [23/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 24 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [24/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 25 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [25/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 26 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [26/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 27 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [27/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 28 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [28/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 29 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [29/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 30 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [30/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 31 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [31/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 32 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [32/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 33 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [33/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 34 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [34/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 35 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [35/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 36 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [36/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 37 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [37/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 38 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [38/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 39 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [39/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 40 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [40/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 41 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [41/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 42 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [42/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 43 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [43/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 44 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [44/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 45 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [45/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 46 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [46/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 47 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [47/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 48 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [48/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 49 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [49/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 50 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [50/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 51 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [51/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 52 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [52/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 53 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [53/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 54 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [54/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 55 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [55/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 56 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [56/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 57 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [57/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 58 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [58/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 59 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [59/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 60 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [60/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 61 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [61/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 62 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [62/63] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 63 (&amp;quot;wrapper&amp;quot; method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\utilities\\utilities.py&amp;quot;, line 19, in asserListItems\nE       self.soft_assert(self.assertEqual, i.text, value)\nE     File &amp;quot;C:\\pycharm-projects\\TestFramworkDemo\\testcases\\test_searchflights.py&amp;quot;, line 32, in test_search_flights_1stop\nE       self.ut.asserListItems(all_stops, stop)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\ddt.py&amp;quot;, line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File &amp;quot;C:\\Users\\pc\\AppData\\Roaming\\Python\\Python312\\site-packages\\softest\\case.py&amp;quot;, line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 1251, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File &amp;quot;C:\\Program Files\\Python312\\Lib\\unittest\\case.py&amp;quot;, line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: &amp;#x27;&amp;#x27; != &amp;#x27;1 Stop&amp;#x27;\nE   + 1 Stop\nE   \nE   \nE   -+ [63/63] +-\n\n------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:149 The chromedriver version (123.0.6312.122) detected in PATH at C:\\seleniumdrivers\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (124.0.6367.62); currently, chromedriver 124.0.6367.91 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\n4\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : 1 Stop\nAssert Passed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : \nAssert Failed\nThe Text is : 1 Stop\nAssert Passed\n\n----------------------------- Captured stderr call -----------------------------\nFriday 26 Apr 2024 22 48 57 PM - LaunchPage - INFO - New York (NYC)\nAll airports\nUnited States\nFriday 26 Apr 2024 22 48 57 PM - LaunchPage - INFO - New York (NYC)\nAll airports\nUnited States\nFriday 26 Apr 2024 22 48 58 PM - LaunchPage - INFO - 29/04/2024\nFriday 26 Apr 2024 22 51 27 PM - SearchFlightResult - INFO - 131\n\n------------------------------ Captured log call -------------------------------\nINFO     LaunchPage:yatraLaunchPage.py:52 New York (NYC)\nAll airports\nUnited States\nINFO     LaunchPage:yatraLaunchPage.py:54 New York (NYC)\nAll airports\nUnited States\nINFO     LaunchPage:yatraLaunchPage.py:71 29/04/2024\nINFO     SearchFlightResult:searchFlightsPage.py:47 131\n\n&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;demo_repo.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>